# Generated by Django 5.1.7 on 2025-05-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0003_alter_category_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_rating',
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(choices=[(0, '0'), (0.5, '0.5'), (1, '1'), (1.5, '1.5'), (2, '2'), (2.5, '2.5'), (3, '3'), (3.5, '3.5'), (4, '4'), (4.5, '4.5'), (5, '5')], decimal_places=1, default=0.0, max_digits=3, null=True),
        ),
    ]
