# Generated by Django 5.1.7 on 2025-05-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0004_remove_product_product_rating_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='product_rating',
        ),
    ]
