# Generated by Django 5.1.7 on 2025-05-16 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0006_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romofyi.customerregistration')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romofyi.product')),
            ],
        ),
    ]
