# Generated by Django 5.1.7 on 2025-05-23 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0008_country_state_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('cus', 'Customer'), ('admin', 'Admin'), ('ven', 'Vendor')], max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='romofyi.role'),
        ),
        migrations.AddField(
            model_name='vendorregistration',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='romofyi.role'),
        ),
    ]
