# Generated by Django 5.1.7 on 2025-05-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0009_role_customerregistration_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerregistration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customerregistration',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.RemoveField(
            model_name='customerregistration',
            name='favorite_product',
        ),
        migrations.RemoveField(
            model_name='customerregistration',
            name='favorite_vendor',
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='favorite_product',
            field=models.ManyToManyField(to='romofyi.product'),
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='favorite_vendor',
            field=models.ManyToManyField(to='romofyi.vendorregistration'),
        ),
    ]
