# Generated by Django 5.1.7 on 2025-05-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0010_remove_customerregistration_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerregistration',
            name='address',
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='customerregistration',
            name='favorite_product',
        ),
        migrations.RemoveField(
            model_name='customerregistration',
            name='favorite_vendor',
        ),
        migrations.AlterField(
            model_name='vendorregistration',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorregistration',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vendorregistration',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorregistration',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorregistration',
            name='shop_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='favorite_product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='favorite_vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
