# Generated by Django 5.1.7 on 2025-05-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0011_remove_customerregistration_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='confirmpassword',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
