# Generated by Django 5.1.7 on 2025-05-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0012_userlogin_customerregistration_confirmpassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(blank=True, choices=[(1, 'Customer'), (2, 'Admin'), (3, 'Vendor')], max_length=20, null=True),
        ),
    ]
