# Generated by Django 5.1.7 on 2025-05-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0013_alter_role_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(blank=True, choices=[('cus', 'Customer'), ('admin', 'Admin'), ('ven', 'Vendor')], max_length=20, null=True),
        ),
    ]
