# Generated by Django 5.1.7 on 2025-06-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0014_alter_role_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RomoUserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('confirmpassword', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('favorite_vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('favorite_product', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
