# Generated by Django 5.1.7 on 2025-06-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0015_romouserregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='romouserregistration',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
