# Generated by Django 5.1.7 on 2025-06-27 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0018_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerregistration',
            name='favorite_product',
        ),
        migrations.RemoveField(
            model_name='customerregistration',
            name='favorite_vendor',
        ),
        migrations.RemoveField(
            model_name='vendorregistration',
            name='product_list',
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, to='romofyi.product'),
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='favorite_vendors',
            field=models.ManyToManyField(blank=True, to='romofyi.vendorregistration'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='romofyi.vendorregistration'),
        ),
    ]
