# Generated by Django 5.1.7 on 2025-06-28 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0020_cartitem_order_orderitem_productreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romofyi.romouserregistration'),
        ),
        migrations.AlterField(
            model_name='searchedproduct',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romofyi.romouserregistration'),
        ),
    ]
