# Generated by Django 5.1.7 on 2025-06-28 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0022_remove_order_vendor_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romofyi.romouserregistration'),
        ),
    ]
