# Generated by Django 5.2.3 on 2025-06-30 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0023_alter_productreview_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchedproduct',
            name='query',
        ),
        migrations.AddField(
            model_name='searchedproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='romofyi.product'),
        ),
        migrations.AlterField(
            model_name='searchedproduct',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='romofyi.romouserregistration'),
        ),
        migrations.AlterField(
            model_name='searchedproduct',
            name='searched_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
