# Generated by Django 5.2.3 on 2025-06-30 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0024_remove_searchedproduct_query_searchedproduct_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romofyi.romouserregistration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romofyi.product')),
            ],
        ),
    ]
