# Generated by Django 5.1.7 on 2025-07-03 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0027_remove_orderitem_vendor_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='romofyi.romouserregistration'),
        ),
    ]
