# Generated by Django 5.1.7 on 2025-07-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0028_orderitem_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
    ]
