# Generated by Django 5.1.7 on 2025-07-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0029_remove_order_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wished_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romofyi.romouserregistration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romofyi.product')),
            ],
        ),
    ]
