# Generated by Django 5.1.7 on 2025-07-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0030_wishlistproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('orderplaced', 'Order Placed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='orderplaced', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('orderplaced', 'OrderPlaced'), ('delivered', 'Delivered'), ('shipped', 'Shipped')], default='Pending', max_length=30),
        ),
    ]
