# Generated by Django 5.1.7 on 2025-07-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0031_orderitem_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
