# Generated by Django 5.1.7 on 2025-07-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0033_remove_comment_product_comment_comment_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('orderplaced', 'OrderPlaced'), ('delivered', 'Delivered'), ('shipped', 'Shipped')], default='pending', max_length=30),
        ),
    ]
