# Generated by Django 5.1.7 on 2025-07-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romofyi', '0034_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
