# Generated by Django 5.1.7 on 2025-07-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_email_payment_order_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='failed', max_length=50),
        ),
    ]
