# Generated by Django 5.2.1 on 2025-05-26 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_id', models.CharField(blank=True, max_length=30, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_color', models.CharField(blank=True, choices=[('RED', 'Red'), ('BLU', 'Blue'), ('GRN', 'Green'), ('BLK', 'Black'), ('WHT', 'White'), ('YEL', 'Yellow'), ('ORG', 'Orange'), ('PNK', 'Pink'), ('PRP', 'Purple'), ('BRN', 'Brown'), ('GRY', 'Gray'), ('GLD', 'Gold')], max_length=100, null=True)),
                ('product_weight', models.CharField(blank=True, choices=[('75g', '75g'), ('50g', '50g'), ('100g', '100g'), ('200g', '200g'), ('500g', '500g')], max_length=10, null=True)),
                ('product_size', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=10, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_oldprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_newprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_rating', models.DecimalField(choices=[(0, '0'), (0.5, '0.5'), (1, '1'), (1.5, '1.5'), (2, '2'), (2.5, '2.5'), (3, '3'), (3.5, '3.5'), (4, '4'), (4.5, '4.5'), (5, '5')], decimal_places=1, default=0.0, max_digits=3, null=True)),
                ('product_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='romoapp.category')),
                ('product_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='romoapp.tags')),
            ],
        ),
    ]
