# Generated by Django 5.2.1 on 2025-05-26 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romoapp', '0002_category_tags_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='romoapp.tags'),
        ),
    ]
