# Generated by Django 5.2.1 on 2025-06-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romoapp', '0004_product_product_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='shop_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
