# Generated by Django 5.2.1 on 2025-06-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romoapp', '0005_appuser_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_isStock',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
